### ISSUE TITLE
continuous notification "The mode has failed while tokenizing the input"

### ISSUE THREAD

**Issue by oxitech239** [KTXSoftware/KodeStudio#19]
- VSCode Version: Kode Studio 1.4.0 (c9038f8e16ebca8ffc83e6dd81e38f0bb8cf1cea, 2016-08-24T18:33:53.502Z)
- OS Version: Linux x64 4.7.0-sabayon

Steps to Reproduce:
1. open any file
2. open another file

**Comment by RobDangerous** [comment]
I've seen that once when somebody copied a new version of Kode Studio into an old Kode Studio directory. Did you maybe do that?

**Comment by oxitech239** [comment]
Hmm, i don't think so.

**Comment by oxitech239** [comment]
I think i better reinstall or build form source or something. I'm having difficulty with kha.khaPath as well. The path is correct but it reports to not find anything in the depth of the path. On top of that <path>/kha contains .current which reads 16.1.2 but the folder reads <path>/kha/16,1,2/

**Comment by oxitech239** [comment]
It's a real mess, nothing of the code i've tried works as expected.

**Comment by oxitech239** [comment]
I think i had been naieve and used the master branch, trying with v16.7.x

**Comment by oxitech239** [comment]
No change, remove ~/.kodestudio, installed from https://github.com/KTXSoftware/KodeStudio/releases/download/v16.7.3/KodeStudio-linux64.zip same message when opening a file "The mode has failed while tokenizing the input"

**Comment by oxitech239** [comment]
This is what i get starting kodestudio from a shell
./kodestudio
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

**Comment by oxitech239** [comment]
Version 16.7.3
Commit e698221ac971850e0a3766dc5bafda21e7ee796d
Date 2016-08-03T19:24:49.649Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

**Comment by oxitech239** [comment]
This is stupifying, i see a tutorial work but none of this works with this version or any other of KodeStudio on Linux ( Sabayon/Gentoo)

**Comment by oxitech239** [comment]
This error is not displayed with vscode when run from http://code.visualstudio.com/docs/?dv=linux64

**Comment by RobDangerous** [comment]
Two things to try: Get the current version (which is 16.8). And don't use haxelib Kha with Kode Studio, that's a super outdated version of Kha which doesn't work with Kode Studio. Don't know how any of that could get you that particular error message though, still worth a try I guess.

**Comment by oxitech239** [comment]
Same problem. All tested.

Honestly, i'd prefer to have an extension for Kha on VsCode than KodeStudio. It's very buggy.

**Comment by RobDangerous** [comment]
Ah, so you are the guy from the forum. I don't understand how you get to the conclusion "it's very buggy" because of a single problematic installation. I'm not interested in providing vscode extensions, Kode Studio has changes to vscode itself which I can not replicate in an extension and I witnessed more than one person who failed to even setup vshaxe correctly (vs one person who failed to get Kode Studio running).
Do you get any additional messages when you run Kode Studio from a terminal? Maybe some .so files are linked to a clib you do not have.

**Comment by oxitech239** [comment]
Thanks for explaining. I've not found a way to diagnose what's going wrong, all i know it's not an issue with vscode.

**Comment by RobDangerous** [comment]
I'm very interested in getting Kode Studio to run everywhere though so I hope you won't run away.
Can you help me out to find the sabayon version you use so I can try myself? 4.7.0 is the kernel version, right?

**Comment by oxitech239** [comment]
Thank's, i'm willing to help in any way i can. Yes , this is a 4.7.x version of the kernel.

I thought of rebuilding it from source but the process is not entirely clear to me.

**Comment by oxitech239** [comment]
What i can do is provide output from strace such as for $strace -f -o kodestudio-strace.log ./kodstudio

Could this be of interest to you?

**Comment by RobDangerous** [comment]
Cool! Yes, strace could prove very useful.

**Comment by oxitech239** [comment]
One of the reasons i entered the rant (sorry) is the extensions also did not load. I'll try and provide the strace feedback asap.

**Comment by RobDangerous** [comment]
Extensions should work fine (though you have to download them manually). Guessing the problems are closely related.

**Comment by oxitech239** [comment]
I just found this: https://forums.bistudio.com/topic/182917-vs-code-sqf-visual-studio-code-sqf-language-release-arma-3-arma-2/ Pointing to a similar but not identical issue.

**Comment by oxitech239** [comment]
@RobDangerous I've finaly come round to uploading an strace output, it's quite big but i assume you'd know what you'd be looking for.

[tracelog_kodestudio.txt](https://github.com/KTXSoftware/KodeStudio/files/552064/tracelog_kodestudio.txt)

**Comment by varomix** [comment]
Hey guys
I just downloaded this in my CentOS 7 box and I get the same error
had nothing before today related to Kha, there's no Haxe related stuff in this machine whatsoever actually hehe.

Running from terminal shows no issues at all.

thanks

**Comment by RobDangerous** [comment]
Hm, about time to fix this. Downloading CentOS...

**Comment by RobDangerous** [comment]
Could finally reproduce. One step further...

**Comment by RobDangerous** [comment]
So, I think it's Linux problem No 1 again - wrong glibc. If you replace resources/app/node_modules/oniguruma/build/Release/onig_scanner.node with the one in vscode 1.7.1 it works fine. Will use an older gcc to build the next release or just copy the libs from the vscode release.

**Comment by varomix** [comment]
oh yes that works, thanks

yeah Centos is not very modern, stays behind a while, I use it because most of the VFX/3D apps I use run better here, most developers use redhat or centos to develop so, less issues when running this apps.

thank you Rob

**Comment by RobDangerous** [comment]
Glad I finally figured it out. @oxitech239 can you test if that fixes it for you, too?

**Comment by oxitech239** [comment]
Awesome, let's have a look

**Comment by oxitech239** [comment]
Confirmed, it fixed the issue. Thanks.
